Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
frequency, wavenumber, momentum, energy = p1()

print(f"The frequency of a photon with wavelength 486.1 nm is {frequency} Hz.")
print(f"The wavenumber, nu-bar, of a photon with wavelength  486.1 nm is {wavenumber} cm^-1.")
print(f"The momentum of a photon with wavelength  486.1 nm is {momentum} kg m/s.")
print(f"The energy of a photon with wavelength  486.1 nm is {energy} Joules.")

assert(isinstance(frequency,float)), "Type Error: The frequency should be a float."
assert(isinstance(wavenumber,float)), "Type Error: The wavenumber should be a float."
assert(isinstance(momentum,float)), "Type Error: The momentum should be a float."
assert(isinstance(energy,float)), "Type Error: The energy should be a float."

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAssertionError[0m                            Traceback (most recent call last)
Input [0;32mIn [3][0m, in [0;36m<cell line: 8>[0;34m()[0m
[1;32m      5[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe momentum of a photon with wavelength  486.1 nm is [39m[38;5;132;01m{[39;00mmomentum[38;5;132;01m}[39;00m[38;5;124m kg m/s.[39m[38;5;124m"[39m)
[1;32m      6[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m"[39m[38;5;124mThe energy of a photon with wavelength  486.1 nm is [39m[38;5;132;01m{[39;00menergy[38;5;132;01m}[39;00m[38;5;124m Joules.[39m[38;5;124m"[39m)
[0;32m----> 8[0m [38;5;28;01massert[39;00m([38;5;28misinstance[39m(frequency,[38;5;28mfloat[39m)), [38;5;124m"[39m[38;5;124mType Error: The frequency should be a float.[39m[38;5;124m"[39m
[1;32m      9[0m [38;5;28;01massert[39;00m([38;5;28misinstance[39m(wavenumber,[38;5;28mfloat[39m)), [38;5;124m"[39m[38;5;124mType Error: The wavenumber should be a float.[39m[38;5;124m"[39m
[1;32m     10[0m [38;5;28;01massert[39;00m([38;5;28misinstance[39m(momentum,[38;5;28mfloat[39m)), [38;5;124m"[39m[38;5;124mType Error: The momentum should be a float.[39m[38;5;124m"[39m

[0;31mAssertionError[0m: Type Error: The frequency should be a float.
AssertionError: Type Error: The frequency should be a float.

